plugins {
    id 'com.android.application'
}
android {
    namespace 'com.estsharion.riyaldollar'
    compileSdk 34
    defaultConfig {
        applicationId "com.estsharion.riyaldollar"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0.0"
    }
}
dependencies {
    implementation 'com.google.androidbrowserhelper:androidbrowserhelper:2.5.0'
}
